name: triple_mixins
description: A set of mixins created to improve development with Triple package
version: 0.0.1
homepage: https://github.com/BlackLeg15/triple_mixins

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_triple: ^1.0.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
